version: '3'
services:
  api:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    command:
      -Des.cluster.name="address-reputation"
